spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rally?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: rally
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: rally

kakao:
  client-secret: W65I5JoQtWrAZ5gavncoIaUJAVvBYFSC
  redirect-uri: http://localhost:8080/auth/kakao/callback
  client-id: 2a01cf694dc7a7696e646d1a023baae0

naver:
  client-id: 1EIgJuGITTkwIj6Na2Iz
  client-secret: t8f_c8jd9l
  redirect-uri: http://localhost:8080/auth/naver/callback

jwt:
  secret: Ymx1ZSBrbm90IGlzIGZhbGxpbmcgaSB3YXMgaG9sZGluZyBvbiBmb3IgeW91

logging:
  level:
    org.apache.catalina: DEBUG
    org.apache.coyote: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG

firebase:
  credentials:
    path: C:\Capstone\GEN_Capstone\rally-eb414-firebase-adminsdk-fbsvc-72e951da9e.json

---
spring:
  config:
    activate:
      on-profile: dev

app:
  dev:
    allow-anonymous: true
    anonymous-evaluator: user002